version: '3'

services:
  web:
    build: .
    restart: unless-stopped
    environment:
      - FLAG
    ports:
      - 80:80
    cap_drop:
      - all
    cap_add:
      - NET_ADMIN  # iptables
      - NET_RAW  # iptables
      - SETGID  # su
      - SETUID  # su
      - AUDIT_WRITE  # su
      - NET_BIND_SERVICE  # nginx / bind
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "5"
